[package]
name = "dcss-data"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dcss_data"
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
serde_json = "1"
rustc-hash = "2.0"
regex = "1.10"

[dev-dependencies]
dcss-api = { path = "/home/eric/Rust/dcss-api/dcss-api" }
dcss-scenario-builder = { path = "/home/eric/Rust/dcss-api/dcss-scenario-builder" }