[package]
name = "dcss-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1", features = ["zlib-ng"], default-features = false }
tungstenite = "0.17"
url = "2"
env_logger = "0.10"
serde_json = "1"
log = "0.4"