name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          default: true

      - uses: extractions/setup-just@v2

      - name: Install dependencies
        run: |

          sudo apt-get install build-essential libncursesw5-dev bison flex liblua5.1-0-dev \
            libsqlite3-dev libz-dev pkg-config python3-yaml binutils-gold python-is-python3 \
            bzip2 ncurses-term locales-all sqlite3 libpcre3 liblua5.1-0 locales autoconf \
            lsof flex libbot-basicbot-perl lua5.1 man libpng-dev python3-tornado

      - name: Build DCSS Webtiles (multiple versions)
        run: just setup-dcss-server

      - name: Run DCSS Webtiles
        run:  |
          python3 crawl/server/server.py &
          sleep 5

      - name: Create users
        run: just dcss-create-users

      - name: Test dcss-api
        run: cd ./dcss-api/ & cargo test successful_connect



          