name: Quarto-Publish

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ericfecteau.ca
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Quarto Build
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: ./dcss-api-docs

      - name: Deploy to website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: ./dcss/dcss-api-docs/
          state-name: ../.ftp-deploy-sync-state.json